### ISSUE TITLE
Default debug configuration?

### ISSUE THREAD

**Issue by hoehrmann** [richterger/Perl-LanguageServer#103]
As a first time user I was rather irritated why starting my script with the debugger would not work without any feedback why not. It then turned out that one needs to manually create a debug configuration and the default settings there worked. As I recall it, other debuggers, including the now defunct vscode-perl-debug extension where I think I added this feature, can provide a suitable default configuration on their own, and the relevant bit probably is https://github.com/pullhub/vscode-perl-debug/blob/variables/src/extension.ts#L183

Would it be possible to add this feature, debug without manually created configuration, to this extension?

**Comment by beltaurus** [comment]
I have gotten in the habit of just switching to the debugger, and hitting the "Create launch.json" link before I attempt to debug my Code.
However, I recommend the Perl Extension to my colleagues all the time, and the first question I usually get is: "Why does my debugger not work?".

It would be nice to address this indeed.

**Comment by richterger** [comment]
Default debug config is implemented in 2.3.0
