### ISSUE TITLE
@ARGV not listed in VARIABLES>Arguments section

### ISSUE THREAD

**Issue by beltaurus** [richterger/Perl-LanguageServer#105]
For any Perl program, we can provide arguments in the launch.json:
```json
        "program": "${workspaceFolder:bin}/program.pl",
        "args": [
          "2021-01-01",
        ],
```

When running the program, I can of course access those arguments in the `@ARGV` array.

However, I was expecting to see them in the Debug side window, under VARIABLES>Arguments?
They are not there:
![image](https://user-images.githubusercontent.com/54114043/124659594-fe9ba180-de59-11eb-943c-e358ac606303.png)

I can of course put this array in my WATCH section:
![image](https://user-images.githubusercontent.com/54114043/124659684-1410cb80-de5a-11eb-9734-db0eb0f306ca.png)

But ideally, the content of the @ARGS variable should just be listed as an array under VARIABLES>Arguments...

**Comment by richterger** [comment]
Fix in 0db06dd3da3a28f6025cbbf8930379ff172c96e7
