### ISSUE TITLE
Problem debugging loop with each statement

### ISSUE THREAD

**Issue by dseynhae** [richterger/Perl-LanguageServer#107]
### Minimal reproducable test case
```
package main 1.0;

my $options = {
  new           => 'zero',
  compiler_args => [ 'one', 'two' ],
  name          => 'three',
};

my %options = %{$options};
while ( my ( $key, $value ) = each %options ) {
  print "<$key>=><$value>\n";
}

1;
```

### Expected behavior

When running the debugger without stepping through the code, we get the expected result:
```
<new>=><zero>
<compiler_args>=><ARRAY(0x7ffff31f6c40)>
<name>=><three>
```
### Problem/Bug
When stepping through the code, the `%options`  hash gets reset, and we keep getting the very first `each` iteration:

![image](https://user-images.githubusercontent.com/54114043/127727812-df6f84bf-fee3-493a-b9dc-e7d37cd0f62f.png)

**Comment by beltaurus** [comment]
I just noticed that if you step (click) fast enough, the each doesn't reset, and we're getting the correct result.
But you don't have time at all to inspect the results between each click.

**Comment by mpetronic** [comment]
I just started using this plug. It is generally very good and thank you for contributing it. I am seeing this same issue in "each" loops.

**Comment by richterger** [comment]
It's fixed and will be in the next release

**Comment by mpetronic** [comment]
Thank you. Look forward to stepping through loops more predictably now. :)
