### ISSUE TITLE
sshArgs should be an array or code re-worked to handle it properly

### ISSUE THREAD

**Issue by willt** [richterger/Perl-LanguageServer#109]
in settings:
```
"perl.sshArgs": [
	"-i", "/home/user/.ssh/id_rsa",
	"-o", "StrictHostKeyChecking=no"
],
```
in the extension code sshArgs are being set like `let sshArgs = config.get('sshArgs') || [];` then further down a push happens.
`sshArgs.push('-l', sshUser, sshAddr, '-L', debug_adapter_port + ':127.0.0.1:' + debug_adapter_port, perlCmd);
        serverArgs = sshArgs.concat(perlArgsOpt);`
This will fail if you just pass a string in from settings.
I can submit a pull request later if you think changing sshArgs to an array is fine. I think it probably is.

**Comment by richterger** [comment]
Fixed in 2.3.0
