### ISSUE TITLE
debugging with module, "step into" does not work

### ISSUE THREAD

**Issue by kstest1** [richterger/Perl-LanguageServer#11]
Created own myutil.pm module and .pl file that  use myutil.
Can run/debug .pl file but if I step into function in .pm, there is a message:

Could not load source 'myutil.pm': Unknow perlmethod _dapreq_source at /usr/local/share/perl/5.22.1/Perl/LanguageServer.pm line 217.

E.g:
.pm:
```
package myutil;
use base 'Exporter';
our @EXPORT = ('findElementByKey');

sub findElementByKey($$$$)  {
...
```

.pl:

```
use myutil;
..
$i=findElementByKey($perl,"Fixed IP Addresses",0,"10.0.1.2");

```

Error: 
`Could not load source 'myutil.pm': Unknow perlmethod _dapreq_source at /usr/local/share/perl/5.22.1/Perl/LanguageServer.pm line 217.
`

**Comment by kstest1** [comment]
Found reason -  path problem. If module is not in "." dir rather in some other dir in @INC, it works.

**Comment by pbrawe** [comment]
How exactly did you fix it? I cannot solve this

**Comment by nametable** [comment]
I think I may be having a similar issue possibly #100, I would like to know how you resolved this @kstest1 also.

**Comment by wielandp** [comment]
I solved it by adding an absolute path to "perl.perlInc": ["./"]
