### ISSUE TITLE
vscode sometimes spins when trying to find definition

### ISSUE THREAD

**Issue by willt** [richterger/Perl-LanguageServer#111]
I'm not sure how to find out what could be causing the issue.
Sometimes when I try to go to definition I get the blue progress bar that scrolls at the top of the screen. I think it usually happens if I switch between tabs and then try to go to definition. It may only happen when the definition isn't found?

I tried turning on debugging and it seemed like the Perl::LanguageServer was sending back a response but maybe vscode never got it or discarded it? If I click anywhere in vscode while this is happening it sends a $/cancelRequest with the same id that Perl::LanguageServer already responded with.

**Comment by richterger** [comment]
That should be fixed in 2.3.0
