### ISSUE TITLE
Is there a way to generate '.vscode/perl-lang' in another place?

### ISSUE THREAD

**Issue by purbam** [richterger/Perl-LanguageServer#113]
When using with VIM, it always generates the directory '.vscode/perl-lang' in the local directory where VIM starts. So, there could be many '.vscode' directories generated.
Is there way to specify another location (like home directory) to put the '.vscode/perl-lang'?
Thanks.

**Comment by richterger** [comment]
An option to speficy the path is implemented in 2.3.0
