### ISSUE TITLE
Debugger: "Invalid variable attributes" when showing array content

### ISSUE THREAD

**Issue by scriplit** [richterger/Perl-LanguageServer#120]
![image](https://user-images.githubusercontent.com/1150969/144758518-6694037d-ca57-49a0-b834-a9be06e327a5.png)

===
Perl: v5.34.0
Perl-LanguageServer-v2.3.0
VS Code:
Version: 1.62.3
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:00:36.721Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.4.0-91-generic (Linux Mint 20.2)

**Comment by phimmi** [comment]
![image](https://user-images.githubusercontent.com/6205744/151420314-69c17421-b17a-4826-8ca4-f0961e6aca80.png)

I tried your provided example and it works as desired.
Please paste in your example in future, so someone from the community can easily test it on their own.

> Version: 1.63.2
> Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
> Date: 2021-12-15T09:39:46.686Z
> Electron: 13.5.2
> Chromium: 91.0.4472.164
> Node.js: 14.16.0
> V8: 9.1.269.39-electron.0
> OS: Linux x64 5.16.1-arch1-1
> Perl LanguageServer: 2.3.0
> Perl: v.5.34.0

**Comment by thGirard** [comment]
@scriplit: could you solve this? I have the very same issue.... 
thank you
Thierry

**Comment by thGirard** [comment]
to be more precise: perl installed with perlbrew. I tried perl 5.34.0 and 5.28.3 not difference.
I have also tried older versions of the debugger: no difference.
The issue persists with all arrays, there the content is only shown as 'invalid variable attributes'.
any help is very much appreciated

**Comment by richterger** [comment]
@thGirard, there are no script and no log file in your posting. Maybe github has striped it from the mail? Can you retry, maybe use the github webinterface, instead of sending a mail.

**Comment by thGirard** [comment]
ah, sorry. here there are. Thank you so much for your support!
[Archive.zip](https://github.com/richterger/Perl-LanguageServer/files/8257479/Archive.zip)

**Comment by richterger** [comment]
@thGirard, could you please try if the following patch fixes the problem (of course you have to adapat the path to your perl installation):
```
Index: /usr/bbsrc/bbbin/usr/lib64/perl5/vendor_perl/5.34/Perl/LanguageServer/Methods/DebugAdapter.pm
===================================================================
--- /usr/lib64/perl5/vendor_perl/5.34/Perl/LanguageServer/Methods/DebugAdapter.pm	
+++ /usr/lib64/perl5/vendor_perl/5.34/Perl/LanguageServer/Methods/DebugAdapter.pm	(working copy)
@@ -545,6 +545,7 @@
                                                                         'package'  => $package,
                                                                          type      => $type}):
                                                     0 ;    
+        $_ -> {name} .= '' ;
         }
 
     return $variables ;
```

**Comment by thGirard** [comment]
thank you! But I am unfortunately naïve with patches. What do I have to do? 
my installation is at: /Users/girard/perl5/perlbrew/perls/perl-5.34.0/bin/perl

tried to google 'apply patch perl' but did not succeed. Sorry

**Comment by thGirard** [comment]
ok, got it! AND IT WORKS
genius! Thank you
<img width="712" alt="Screenshot 2022-03-18 at 22 31 51" src="https://user-images.githubusercontent.com/65077231/159085727-67351da8-7054-4d4e-879a-fd86da997e10.png">

**Comment by dseynhae** [comment]
The single-line patch works great for me as well...

How often should we expect releases? I'm just wondering if I should just build this Perl Module myself, or if I can just wait for the next release.
