### ISSUE TITLE
No way to pass options to debug runner from launch.json

### ISSUE THREAD

**Issue by mpetronic** [richterger/Perl-LanguageServer#125]
I would like to be able to setup a launch configuration to pass the equivalent of "perl -I/some/module/path" when debugging. For various reasons, I don't want to use PERL5LIB or any "use lib /some/path" in the code. Other application launchers sometimes include launch options like "runtimeArgs" as an array of values to be passed into the launch runner which are separate and different from the typical "Args" that are passed into the script.pl that is being run. This does not appear to be supports by this plug.

Is there any way to do this with this extension that I might be missing?

**Comment by richterger** [comment]
Just use the `perlInc` setting. That's an array and all elements will be added with `-I` to the perl commandline
