### ISSUE TITLE
Wide character in source code causes perltidy fail

### ISSUE THREAD

**Issue by jamadam** [richterger/Perl-LanguageServer#127]
Visual Studio Code Version: 1.63.2
Perl::LanguageServer 2.3.0
Perl 5.28.3

## Steps to reproduce the behavior

Copy the following code into vscode editor, select the line and then run "Format Selection" via right click.

```
my  $var = '♥';
```

The following error is displayed on OUTPUT panel.

```
Wide character in syswrite at /path/to/perl-5.28.3/lib/site_perl/5.28.3/darwin-2level/AnyEvent/Util.pm line 661.
```

This may not be a right solution but works for my project.

https://github.com/jamadam/Perl-LanguageServer/commit/c47498899b620a11d843f2f3e8f5f4e1e4ad8f2f

**Comment by ecos-ps** [comment]
Looks good to me. Why don't you file a Pull Request? I think that the author will have a look at it as soon as he has some free time.
