### ISSUE TITLE
How could I use this in VSCodium?

### ISSUE THREAD

**Issue by Skeeve** [richterger/Perl-LanguageServer#134]
Can't find it in vscodium's marketplace.

**Comment by richterger** [comment]
I will consider publishing it there for the next release, until then you can install it via .vsix file:

https://code.visualstudio.com/docs/editor/extension-marketplace#_install-from-a-vsix

**Comment by richterger** [comment]
2.6.1 is now pulished on https://open-vsx.org/extension/richterger/perl
