### ISSUE TITLE
how to debug programs running as different users?

### ISSUE THREAD

**Issue by wielandp** [richterger/Perl-LanguageServer#141]
Maybe not only in my case the running program belongs to another user.
Normally I run for debugging "sudo -u www-data QUERY_STRING=something perl -d program.pl"

I have patched DebuggerProcess.pm with a hard coded user.

How to create an option for the debugging "sudouser"?

**Comment by wielandp** [comment]
I created a pull request https://github.com/richterger/Perl-LanguageServer/pull/165

**Comment by richterger** [comment]
Implemented in 432c7c94ccd57e622c8740d8635094bfe68cb54b (pull request #174)
