### ISSUE TITLE
Comment not recognized when using x flag on regular expressions

### ISSUE THREAD

**Issue by dseynhae** [richterger/Perl-LanguageServer#142]
Consider the following code which strips information out of a line:

```perl
  $line =~ s{
      \s*        # Strip trailing blanks
      \\?        # => Optional continuation character
   $}{}smx;
```

It was written taking advantage of the `x`flag, which ignores white-space (including comments)

However, the VS Code editor doesn't understand that the comments are really active comments, and not part of the pattern:

![image](https://user-images.githubusercontent.com/54114043/168699179-d9d553ba-90c8-4414-a917-c573d5e28913.png)

Note that the real comments on the other lines are recognized (faded color).
I would expect the comments within the `x` flagged pattern also to be recognized.

**Comment by richterger** [comment]
The syntax colors are not part of the Perl::LanguageServer, but done by vscode itself. So this is the wrong place to ask.
