### ISSUE TITLE
debug

### ISSUE THREAD

**Issue by daihanhle** [richterger/Perl-LanguageServer#144]
Hi,
I can not get debug working

here is my setup for launch.json:
{

    "version": "0.2.0",
    "configurations": [       
        {
            "type": "perl",
            "request": "launch",
            "name": "Perl-Debug",
            "program": "${file}",
            "stopOnEntry": true,
            "reloadModules": true,
        }
    ]
}
nothing happen
I use per 5.18 on centos

**Comment by richterger** [comment]
Should be fixed in 2.5.0
