### ISSUE TITLE
Go to definition for function in the same file does not work

### ISSUE THREAD

**Issue by gtataranni** [richterger/Perl-LanguageServer#148]
subroutines in the same file are not identified. For subs imported, the go-to definition works

**Comment by richterger** [comment]
It works for me. So please provide some more information what is not working. I am not able to read your mind... (sorry, for that).

**Comment by gtataranni** [comment]
I'm sorry, I am not able to reproduce this consistently. It works fine on small files, however on larger and more complex scripts/modules jumping to the definition of a sub that is in the same file does not work.

I will close the issue for the time being, and in the meantime I will try to get a MRE. Once I have it, I will reopen this or open a new one.

**Comment by gtataranni** [comment]
I'm sorry, I am not able to reproduce this consistently. It works fine on small files, however on larger and more complex scripts/modules jumping to the definition of a sub that is in the same file does not work.

I will close the issue for the time being, and in the meantime I will try to get a MRE. Once I have it, I will reopen this or open a new one.
