### ISSUE TITLE
Doesn't work with Perl 5.22+

### ISSUE THREAD

**Issue by LinoBarreca** [richterger/Perl-LanguageServer#151]
Since AnyEvent 7.17 (latest) is compatible with Perl < 5.22, any newer version of Perl can't run the LanguageServer 2.3.0 (latest)
Is a fix expected?

**Comment by richterger** [comment]
You need to install the AnyEvent::IO and Coro. Just ignore the warning that it might not work. For Perl::LanguageServer it works fine. I am using it with Perl 5.26, 5.32 and 5.34 (amog other Perl versions)
