### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by bmeneg** [richterger/Perl-LanguageServer#154]
Hi @richterger,

I see the language server had many updates and fixes since the last release (2.3.0), would you mind creating a new release so people can stay up to the new fixes when installing the module directly from metacpan?

Thanks.

**Comment by richterger** [comment]
I wanted to do this already, just a matter of a little free slot in my timetable. I am working on it...

**Comment by bmeneg** [comment]
I really appreciate it @richterger!
Will be waiting for that :-)
