### ISSUE TITLE
Perl Debug does not start with vscode 1.74.0

### ISSUE THREAD

**Issue by pmqs** [richterger/Perl-LanguageServer#158]
## My Setup

Running vscode: 1.74.0 on Ubuntu 22.04

Perl is 5.30.2
Perl vscode extension 2.4.0

Not running in a container

## The problem

A Perl debug session terminates immediately with no error message. This was working with vscode 1.73

### Debug Console

```
Platform: linux
Launching program in terminal and waiting
Inactive RemoteSession
```

### Perl Debug Log
```["2022-12-11T20:07:36.091Z","perl-debug.debug","Platform: linux"]```

### Perl Language Server

logging level set to 2 -- this is all that output when I run run `F5` to start a new debug session. There is a pile of startup logging 

```##### 70 #####
 running: {} coros: {}
```

Port `13603` for the Perl language server is active

```
$ sudo lsof -i -P -n | grep 13603
perl      12812            xxxx  3u  IPv4  68836      0t0  TCP 127.0.0.1:13603 (LISTEN)
```
Have tried reverting to vscode 1.73 but still experiencing the same issue. Also reinstalled the vscode Perl extension.

Any suggestions for how to root-cause this issue?

**Comment by knutov** [comment]
I had the same issue after latest vscode update.

I fixed this by going to settings of extension and resetting setting about port number to default. 

I did not investigate, but looks like data format about port number was changed in config.

**Comment by pmqs** [comment]
> I had the same issue after latest vscode update.
> 
> I fixed this by going to settings of extension and resetting setting about port number to default.
> 
> I did not investigate, but looks like data format about port number was changed in config.

Thanks @knutovl, but already tried that without any change to the issue. 

Also tried uninstalling vscode & the perl extension with no change.

I've temporarily removed the `~/.config/Code` directory tree and tried a small example Perl debug --  that worked. perfectly. Only problem with that is it wipes all my config for other extensions, so I'm only going to do that if there is no other option.

Going to see if I can figure out what part of the enormous Code directory tree is causing the issue. Any hints would be welcome.
