### ISSUE TITLE
[question] How to disable .vscode/perl-lang?

### ISSUE THREAD

**Issue by Freed-Wu** [richterger/Perl-LanguageServer#176]
Comes from <https://github.com/bmeneg/coc-perl/issues/17>. TIA!

**Comment by richterger** [comment]
Set `perl.disableCache` to true

**Comment by Freed-Wu** [comment]
Is it possible to allow user change cache path to another path?

Such as edit `/dev/shm/a.pl` will create cache in `~/.cache/perl-lang/%dev%shm%a.pl`. Not only it can support cache to fasten, but also allow user to edit any file in readonly directories.
