### ISSUE TITLE
Syntax checker uses local path rather than mapped path when running in docker

### ISSUE THREAD

**Issue by CassWindred** [richterger/Perl-LanguageServer#178]
Having issues with the syntax checker in VSCode failing in compilation when an imported file uses an `import` subroutine because the filename of the calling/importing file is not correct as provided by the core call:

`my ($package, $filename) = CORE::caller;`

as shown by immediately calling `warn "Import Filename: ".$filename;`

This filename for some reason contains the path of the file on the local system - this then results in an error later on like

`Error resolving realpath on '[local path to file]': No such file or directory at [file being imported]`

Not entirely sure how this is happening, the fact that the file cannot be found suggests that the import is being run inside the docker container, but it seems the Perl Syntax checker is somehow passing in the path for outside the docker container. Running `perl -c [importing file]` and `perl -c [imported file]` as well as just running them with `perl` alone both resolves fine, so it seems the VSCode extension is doing something weird.

**Comment by richterger** [comment]
Perl::LanguageServer cannot know how to map path inside and outside the container. You have to set `perl.pathMap`

e.g.

```json
"perl.pathMap": [
    [
	"file:///path/inside/the/container",
	"file:///local/path/outside/the/container"
    ]
]
