### ISSUE TITLE
Debug output to stdout/stderr is buffered until the end of the script

### ISSUE THREAD

**Issue by beltaurus** [richterger/Perl-LanguageServer#19]
Consider the silly proxy for the problem:
```
package main 1.0;
use 5.010;
use strict;
use warnings;
use Carp;

my @array = ( 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0 );
for (@array) {
    say or croak 'I can not talk right now';
}

1;
```

When running the debugger in VS Code, stepping through the loop will not produce any result on the Debug Console... As a matter of fact, the output won't be flushed until the end of the script.

Obviously, I can change that behavior by forcing the flush in the beginning of my script:
```
$|=1;
```

However, shouldn't that be the default behavior of a debugging cycle? (we can still make it optional, but I suspect that most people debugging would expect the forced flush to be the default).

I see the same problem with much larger and complex scripts, indicative that the buffer for the output must be rather large... Wouldn't it make sense to make this buffer 0 (for immediate flush)

**Comment by richterger** [comment]
stdout is now unbuffered while debugging, see commit c7fd78332037dacb43fe1bd7a9edc381a55e9a8f
