### ISSUE TITLE
Incorrect syntax highlighting

### ISSUE THREAD

**Issue by annulen** [richterger/Perl-LanguageServer#192]
In the following fragment `elsif` line is highlighted incorrectly in VSCode — `#` is treated as a beginning of the comment (just like what GitHub highlighter is doing):
```perl
    while (<$fh>) {
        if (/^#\s*RUN:(.*)$/) {
            push @commands, $1;
        } elsif (!/^#\sCOM:/) {
            push @expected, $_;
        }
    }
```

**Comment by richterger** [comment]
Perl::LanguageServer has nothing do to with syntax highlighting. That's done by vscode itself.
