### ISSUE TITLE
FindBin does not give correct path in language server

### ISSUE THREAD

**Issue by harmic** [richterger/Perl-LanguageServer#2]
I've got some perl executables that set the path to include a directory relative to the executable itself, using FindBin like so:

`
use lib "$FindBin::Bin/..";
`
This seems a fairly common pattern.

However the language server reports errors, saying it can't find the modules that the script is trying to import from that path.

The error message is:

`
Can't locate xxxxxx in @INC (@INC contains: yyyyy/.. etc)
`

where yyyyy is the root workspace directory rather than the directory which the contains the script being checked.

**Comment by richterger** [comment]
That will not work, because when doing syntax check of a module it is not know which binary will execute and call the module.

Use "perl.perlInc" setting to set your correct include path. 

See also #1

**Comment by bmartin** [comment]
I was able to fix this in my copy by adding:

```perl
--- a/Perl/LanguageServer/SyntaxChecker.pm
+++ b/Perl/LanguageServer/SyntaxChecker.pm
@@ -140,6 +140,8 @@ sub background_checker
         $text = eval { Encode::encode ('utf-8', $text) ; } ;
         $self -> logger ($@) if ($@) ;    
     
+        my ($file) = ($uri =~ m{^file://(.*)});
+        $text = "local \$0; BEGIN { \$0 = '$file'; if (\$INC{'FindBin.pm'}) { FindBin->again(); } }\n# line 1 \"$file\"\n" . $text;
         my $ret ;
         my $errout ;
         my $out ;
```
This fixes `$0`, `FindBin:*`, and `__FILE__`. See [perlsyn Plain-old-comment (not!)](https://perldoc.perl.org/perlsyn.html#Plain-Old-Comments-(Not!)]) for how it fixes `__FILE__` and `__LINE__`. 

It feels like this is probably function is probably the wrong place to put this fix.
