### ISSUE TITLE
Expose new command: "Perl: Restart Language Server"

### ISSUE THREAD

**Issue by Nowaker** [richterger/Perl-LanguageServer#29]
Other language servers do it too:

![image](https://user-images.githubusercontent.com/611746/85189455-ebc92580-b274-11ea-8ced-f3d47ebd0eb8.png)

It's useful in situations when one is trying to get the language server running but is hitting some problems. Currently, there's no easy way to instruct the extensions to attempt to start the language server again.

Also, when the language server is run remotely, and the server where it's running goes down for a minute or two, one has to restart VS Code to get the language server back.

**Comment by beltaurus** [comment]
Doesn't the language server start again when you reload the workspace?

**Comment by richterger** [comment]
Please just use the Command Reload Window
![grafik](https://user-images.githubusercontent.com/2469607/91645111-bb56f200-ea42-11ea-8f00-7426ca37c617.png)
