### ISSUE TITLE
Perl::LanguageServer - Support for Perl v5.16

### ISSUE THREAD

**Issue by bmingles** [richterger/Perl-LanguageServer#36]
It looks like Perl::LanguageServer requires Perl v18. We are constrained to some outdated servers. Would it be possible to make this work in v5.16?

**Comment by richterger** [comment]
It should also work with Perl 5.16, the reason for 5.18 is that some of the 
modules that gets used requires 5.18. If you have all required module for 
5.16, than you can change the use 5.18 to use 5.16 and if it a try

**Comment by thalia2809** [comment]
@richterger thanks. I have the same problem but I am not sure how to force the use of perlv v5.16
can you please explain how to check if I have all requires modules installed and how I can change the LanguageServer version?
Thank you

**Comment by finwarman** [comment]
> @richterger thanks. I have the same problem but I am not sure how to force the use of perlv v5.16 can you please explain how to check if I have all requires modules installed and how I can change the LanguageServer version? Thank you

I've created a fork of this module with Perl v5.16 compatibility, if you're unsure how to edit it yourself:

https://github.com/finwarman/perl-5.16-Perl-LanguageServer/releases/tag/V2.3.0

**Comment by bgeels** [comment]
Hi @finwarman, thank you for putting that patch together. Using that I was able to get the Language server installed and mostly working with perl 5.16. However, the debugger is not currently working. When attempting to run the code. The following error message is printed:

```
No DB::DB routine defined at...
```

It's my understanding that `DB::DB` is provided by Perl-LanguageServer. I was wondering if you ran into this issue with version 5.16 and were able to get around it?
