### ISSUE TITLE
Cannot install on Windows 10

### ISSUE THREAD

**Issue by f-w** [richterger/Perl-LanguageServer#38]
```
C:\Users\me>cpan Perl::LanguageServer
...
t/80_ssltest.t ............. 1/415
#   Failed test 'server_error <An established connection was aborted by the software in your host machine.>'
#   at t/80_ssltest.t line 37.
# Looks like you failed 1 test of 415.
t/80_ssltest.t ............. Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/415 subtests
t/81_hosts.t ............... ok
t/handle/01_readline.t ..... ok
t/handle/02_write.t ........ ok
t/handle/03_http_req.t ..... skipped: PERL_ANYEVENT_NET_TESTS environment variable not set
t/handle/04_listen.t ....... ok

Test Summary Report
-------------------
t/80_ssltest.t           (Wstat: 256 Tests: 415 Failed: 1)
  Failed test:  6
  Non-zero exit status: 1
Files=83, Tests=602, 16 wallclock secs ( 0.34 usr +  0.38 sys =  0.72 CPU)
Result: FAIL
Failed 1/83 test programs. 1/602 subtests failed.
gmake: *** [Makefile:899: test_dynamic] Error 255
  MLEHMANN/AnyEvent-7.17.tar.gz
  C:\strawberry\c\bin\gmake.exe test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports MLEHMANN/AnyEvent-7.17.tar.gz
Stopping: 'install' failed for 'AnyEvent'.
```

**Comment by beltaurus** [comment]
I just had a situation where I ran into a very similar problem, installing with `cpanm` on WSL (So I wanted the WSL-Ubuntu-18.04 configuration to work).

The installation of Perl::LanguageServer failed, and when I checked the log file, I noticed it was a failing test...
So I ran again, this time skipping all testing:

```
cpanm -n Perl::LanguageServer
```

**This _installed_ the Perl Language server successfully**, but when trying to use it, it didn't work (modules not found on `@INC`), until I added 3 modules to my Perl installation. I'm surprised that those PM modules weren't installed as dependencies for the Perl::LanguageServer module.
(I will submit this as a separate error).

**Comment by richterger** [comment]
This Test Problem for AnyEvent should cause you trouble, but LanguageServer does not correctly work on windows.

Basicly LanguageServers run on Windows, but because of issues with Perl and reading stdin in a non blocking way and capturing the output of perl -c in a non blocking way, you might get high CPU load and sometimes the LanguageServer seems to get stuck and will continue after you have made same changes.
Because of this basic issues I gave up after spending a lot of time trying to get it working on windows.

**Comment by alexchandel** [comment]
Given that every other language server works fine on Windows, seems like this is a Perl-specific problem rather than a Windows problem.
