### ISSUE TITLE
[QUESTION] Getting started

### ISSUE THREAD

**Issue by mictian** [richterger/Perl-LanguageServer#4]
Hi,

I am a completely beginner with Perl. I just installed 'Perl' plugin in vs code, and without any error or message of any kind I do not have the provided features of this plugin.
For example 'Go to Definition' does not work.

* How can I troubleshoot this? 
* Is there any log that I can see? Where?

P.S. I have already run `cpan Perl::LanguageServer`.

Regards,
Mictian

**Comment by richterger** [comment]
Could you please retry with Version 2.0, which was just released
If it is still not working, goto the output pane and choose Perl LangaugeServer and post the output

**Comment by mictian** [comment]
Hi @richterger,
I can tell you that it work much better now!!

THANK YOU very much 👍
