### ISSUE TITLE
Please add github repository to module metadata

### ISSUE THREAD

**Issue by oalders** [richterger/Perl-LanguageServer#43]
I actually had to use Google to find this repo. 😄 

I think this is still a pretty good summary of how to do this: https://perlmaven.com/how-to-add-link-to-version-control-system-of-a-cpan-distributions

It would be nice to have a link right to the repository from the MetaCPAN sidebar.

**Comment by chrstphrchvz** [comment]
This was added in #32, so all that should be needed is to upload a new release to CPAN.

**Comment by oalders** [comment]
Sorry -- I didn't see this in the code. Great!
