### ISSUE TITLE
Variable pane in debugger doesn't show references as references

### ISSUE THREAD

**Issue by beltaurus** [richterger/Perl-LanguageServer#45]
### Problem Description
Consider the debug information from debugging a script attached below:
![image](https://user-images.githubusercontent.com/54114043/92511128-bec84700-f1c1-11ea-8e75-1bf77232f8bb.png)

When I look at the value of a REFERENCE in the `Locals` section, I would like to see the actual value for that reference (an address).

With the current debugger implementation, there is no indication that my `$*_ref` variables *ARE* references (except through my naming discipline). 

Also: 

- It looks like code references aren't even displayed at all in the `Locals` pane.
- When I add an expression for this code reference, it doesn't show its value...

I can understand that some people actually are interested in the dereferenced content of those variables...
Well, they can add a dereference expression in the `WATCH` pane...

### Code to reproduce
```perl
package basics 1.0;
use 5.010;
use strict;
use warnings;

# Definitions
my $scalar = 'Hello Perl World';
my @array  = ( 'Hello',    'Perl',  'World' );
my %hash   = ( 'greeting', 'Hello', 'object', 'Perl', 'location', 'World' );

sub code {
    my ( $greeting, $object, $location ) = @_;
    say "$greeting $object $location";
    return;
}

# References
# Can be used to pass object around as scalar

my $scalar_ref = \$scalar;
my $array_ref  = \@array;
my $hash_ref   = \%hash;
my $code_ref   = \&code;

say ref $scalar_ref;
say ref $array_ref;
say ref $hash_ref;
say ref $code_ref;

## Object Dereference (object sigil)
my $scalar_copy = ${$scalar_ref};
my @array_copy  = @{$array_ref};
my %hash_copy   = %{$hash_ref};

say ${$scalar_ref};

my $index = 0;
foreach my $s ( @{$array_ref} ) {
    say $s;
    say ${$array_ref}[ $index++ ];
}
print "\n";

foreach my $k ( keys %{$hash_ref} ) {
    say $k;
    say ${$hash_ref}{$k};
}

&{$code_ref}( 'Hello', 'Perl', 'World' );

1;

```

**Comment by beltaurus** [comment]
Appropriate information display by the debugger is even more important for blessed references...
I would like to see exactly what it such a reference looks like when printed:
```
LIBRARY::PATH::TO::MODULE=HASH(0x37ff990)
```

Which class that was used for the blessing is crucial information, especially when building factory classes...

**Comment by richterger** [comment]
Scalar References are not displayed due to limitation of the perl debugger. I guess it can be done, but it is a lot of extra work.
I don't see any benefit of displaying HASH(0x1234). In most cases yo don't need to know the address, but it take space, so the important informations (content of the hash) might been hidden.
For classes (e.g. LIBRARY::PATH::TO::MODULE) the blessed name is still shown.
If you need the address of an hash, just add "$hash_ref" to the watch expressions.
