### ISSUE TITLE
Array last index shows as '-1' in debugger

### ISSUE THREAD

**Issue by beltaurus** [richterger/Perl-LanguageServer#48]
Take any regular array:
```
my @array = qw(hello Perl World);
print @array . "\n";
print $#array . "\n";
```

The scalar context for this array gives 3,
and the last index shows 2.
As expected.

However, in the debugger:
In the watch list:
![image](https://user-images.githubusercontent.com/54114043/94562870-b9877680-021a-11eb-8d46-977a62d47628.png)

In the Debug Console:
![image](https://user-images.githubusercontent.com/54114043/94562922-d1f79100-021a-11eb-8176-77a7a2df096c.png)

Although technically correct (-1 can be used to access the last element), I would expect the debugger to reveal the REAL index number, as used in:
```
for my $i (0..$#array) {
  ...
}
```
... or as in how it is printed out, naturally...

**Comment by richterger** [comment]
Fixed in V2.3.0
