### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by Mordef** [richterger/Perl-LanguageServer#5]
Package (.pm) not found 
use Bar; <-- Not found (Ctags found it in same folder)

Go To Definition -> not found when on "use Bar."
my $foo = Bar::new; <-- found all "new"not only Bar::new

With active Ctags:
![grafik](https://user-images.githubusercontent.com/22061464/72785042-853ecd80-3c2a-11ea-8be2-147fcf393bfc.png)

Without CTags
![grafik](https://user-images.githubusercontent.com/22061464/72785074-9ee01500-3c2a-11ea-94a9-a48f8176682f.png)

**Comment by richterger** [comment]
Packages are searched in the same way as Perl does it by using the perl library path (@INC).
You can add directories to the default library path by using the setting

* `perl.perlInc`: array with paths to add to perl library path

 Goto Definition does not honour package names yet, that is planed for one of the next releases.
