### ISSUE TITLE
Arguments don't show up in debugger

### ISSUE THREAD

**Issue by beltaurus** [richterger/Perl-LanguageServer#53]
With the following in my `launch.json`:
```
			"program": "${workspaceFolder}/${relativeFile}",
			"args": [
				"--date=2020-09-30",
			],
```
If I add the corresponding Perl variable in the WATCH widget, it looks like the arguments take:
![image](https://user-images.githubusercontent.com/54114043/95404838-ff070c00-08ca-11eb-944b-baa164a9dccc.png)

However, when looking under the VARIABLES widget, the arguments are missing:
![image](https://user-images.githubusercontent.com/54114043/95404895-252cac00-08cb-11eb-997b-b5e7ba40cadf.png)

**Comment by richterger** [comment]
Arguments are now shown in V2.3.0
