### ISSUE TITLE
langserver.org doesn’t list Perl::LanguageServer

### ISSUE THREAD

**Issue by FGasper** [richterger/Perl-LanguageServer#57]
Hello,

It would be good for this module—and Perl as a whole!—for this module to be listed on langserver.org’s table of implementations.

If you’d like, I can submit the PR there if you’ll take a glance and say which features in the table it supports.

**Comment by richterger** [comment]
Yes, please go ahead and add it. The following features are currently supported:

- Jump to def
- Workspace symbols 
- Find references 
- Diagnostics 
- Additional capabilities
-- outline view
-- signature help
-- debugger

**Comment by clscott** [comment]
I have added a pull request
https://github.com/langserver/langserver.github.io/pull/240

**Comment by richterger** [comment]
Thanks!
