### ISSUE TITLE
Go to Definition does not work for multiple variable declaration

### ISSUE THREAD

**Issue by utgwkk** [richterger/Perl-LanguageServer#58]
## Step to reproduce

1. Hover over `$b` of the following code
2. Run "Go to Definition"

```perl
use strict;
use warnings;

sub sum {
    my ($a, $b) = @_;

    return $a + $b;
}

print sum(3, 5);
```

## Expected behavior

Jump to line 5 (the line of `my ($a, $b) = @_;`)

## Actual behavior

No definition found for 'b'.

**Comment by richterger** [comment]
Goto Definition is turned off for local variables (ie. delcared via my) by default. You can enable it with showLocalVars setting.
