### ISSUE TITLE
Suggestion: introduce perltidy for code formatting of this repository

### ISSUE THREAD

**Issue by utgwkk** [richterger/Perl-LanguageServer#59]
Code formatting would make code of this repository more readable and easy to contribute.

It does not mean that I suggest to combine this language server with perltidy for implementing [document formatting](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_formatting) (but it would be useful too).

**Comment by beltaurus** [comment]
I've always thought of the following as very distinct categories in VS Code:
1. Editing/Debugging (syntax management, semantic management)
2. Problem detection (code errors, coding style problems)
3. Formatting

as such, a Language Server (with Debugging API) serves the first bullet.

There already is an extension that addresses the third problem (and it actually uses your PerlTidy installation).

So I'm not sure what we would gain by trying to address a formatting issue with an edit extension?

Maybe my premise on the architecture is wrong, though...

**Comment by utgwkk** [comment]
What I want to suggest is to format the language server's code (under `lib/` directory) with perltidy, not to add a new feature of integrating perltidy with language server.

I know there are already VSCode extension using perltidy in the marketplace (such as [Kaktus.perltidy-more](https://marketplace.visualstudio.com/items?itemName=Kaktus.perltidy-more)). So I think integrating this language server with perltidy is not necessarily needed (and your premise on the architecture is not wrong!)

**Comment by beltaurus** [comment]
I whole-heartedly agree then.
I refuse to review any Perl code that has not passed PerlCritic and PerlTidy.

**Comment by richterger** [comment]
Sorry for using a different codeing style than you do. As soon as perltidy would be able to support my formatting style, I am happy to use it. As long as it forces me to write my code in a way that is, from my point of view, much harder to read, I will not do.
