### ISSUE TITLE
Language server dies if there are any corrupt json cache files

### ISSUE THREAD

**Issue by bmartin** [richterger/Perl-LanguageServer#6]
I'm not exactly sure how it happened, but I had a corrupted json file in the .vscode/perl-lang folder. Possibly from quitting in the middle of editing.

I was able to work around it in my local copy by adding an eval like the one below that simply ignores the cache if it does not parse correctly. It may also be worthwhile to modify cache writing to be atomic.

```
diff --git a/.../Perl/LanguageServer/Parser.pm b/.../Perl/LanguageServer/Parser.pm
index 8034b2cc7c..9cb57afc55 100644
--- a/.../Perl/LanguageServer/Parser.pm
+++ b/.../Perl/LanguageServer/Parser.pm
@@ -332,11 +332,18 @@ sub _parse_perl_source_cached
             #print STDERR "load from cache\n" ;    
             my $cache ;
             aio_load ($cachepath, $cache) ;
-            my $vars = $Perl::LanguageServer::json -> decode ($cache) ;
+            my $vars;
+            # Ignore any corrupt json files
+            eval {
+                $vars = $Perl::LanguageServer::json -> decode ($cache) ;
                 $stats -> {loaded}++ ;
+            };
+            if (defined $vars)
+                {
                 return $vars ;
                 }
             }
+        }
 ```

**Comment by richterger** [comment]
You are right and I added this eval already in Version 2.0.2 of Perl::LanguageServer.

All reading and writing of the symbol cache is done by one single thread so there should no need to make it atomic, because it will always happen one after each other.
