### ISSUE TITLE
Question: Disable Symbol list provider

### ISSUE THREAD

**Issue by carlosfrodriguez** [richterger/Perl-LanguageServer#61]
Hi @richterger 

As some times the symbol table is stuck, is there a possibility to disable it from this extension in order to use another provider for the symbol list?

((enjoy))
cr

**Comment by richterger** [comment]
You can disable the whole extention, because the whole extesion was getting stuck. Hopefully this issue is solved with commit c3e8670c41a28027b27dbe5d9a8394c49ce640c7
