### ISSUE TITLE
DeprecationWarning: Buffer() is deprecated

### ISSUE THREAD

**Issue by beltaurus** [richterger/Perl-LanguageServer#64]
The full error message is:
```
(node:25414) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

I'm not sure what is causing this, but the symptom is that a couple of times in a day of debugging, the outline in  vs code stops working:
```Loading document symbols for `<my_module>`
```

I need to reload my VS Code window to get the LS up and running again. I consistently get the error message about the Buffer() command in my Language Server for Perl console.

I'm thinking that this problem might be resolved by just taking care deprecated use of Buffer?

**Comment by richterger** [comment]
I never have seen this Buffer message, so I am not able to fix it.
That the LanguageServer got stuck should be fixed in commit c3e8670c41a28027b27dbe5d9a8394c49ce640c7
