### ISSUE TITLE
Unknow perlmethod _rpcnot_setTraceNotification

### ISSUE THREAD

**Issue by marema31** [richterger/Perl-LanguageServer#71]
When I start a local debug session, it stop without doing anything. 

In the Output I see
```
LS: end aio read cnt=98
LS: line=<Content-Length: 76>
LS: line=<>
LS: read data={"jsonrpc":"2.0","method":"$/setTraceNotification","params":{"value":"off"}}
LS: read header={ "Content-Length" => 76 }
LS: ---> Request: {
   "jsonrpc" : "2.0",
   "params" : {
      "value" : "off"
   },
   "method" : "$/setTraceNotification"
}

LS: handle_req id=
LS: method=_rpcnot_setTraceNotification
LS: ERROR: Unknow perlmethod _rpcnot_setTraceNotification at /usr/local/share/perl/5.20.2/Perl/LanguageServer.pm line 217.
```

I'm using Perl::LanguageServer 2.10 on debian 10.

**Comment by richterger** [comment]
`ERROR: Unknow perlmethod _rpcnot_setTraceNotification` is not an issue, that just means that not all features of the debugging protocol are implemented. Also it say ERROR, it's just a warning.

The debugger sometime stop a random places, that is caused when a module is load which contains a breakpoint. This is still on my todo list, but simply continue the debug session works.
