### ISSUE TITLE
Jump into module

### ISSUE THREAD

**Issue by pbrawe** [richterger/Perl-LanguageServer#75]
Whenever I try to jump into a local module, it says: 
Could not load source 'RPG/Linter.pm': Unknow perlmethod _dapreq_source at /home/bensen/perl5/perlbrew/perls/perl-5.24.4/lib/site_perl/5.24.4/Perl/LanguageServer.pm line 217.

I've tried including my modules in perl.perlInc in settings.JSON but that didnt help.

`use lib 'RPG';
use RPG::Linter;`

`$linter->print_json($errors);`

The code produces the correct outcome, also when debugged. But i cannot visually debug it.

**Comment by richterger** [comment]
the `Unknow perlmethod _dapreq_source` is not an error, but just a warning. You can savely ignore it, but you need either use an absoult path in your `use lib`, or use `cwd `config option to set the working directory.
