### ISSUE TITLE
Server hangs at cyrillic  encoded string

### ISSUE THREAD

**Issue by ragnayev** [richterger/Perl-LanguageServer#76]
Hi,

A file with program code:
`
use strict;
use warnings;

print "А";
`
A - is in Cyrillic encoding. When trying to save the file, the server produces a lot of records in a log file:

EV: error in callback (ignoring): Wide character in syswrite at /usr/local/lib/x86_64-linux-gnu/perl/5.28.1/AnyEvent/Util.pm line 661.
EV: error in callback (ignoring): Wide character in syswrite at /usr/local/lib/x86_64-linux-gnu/perl/5.28.1/AnyEvent/Util.pm line 661.
EV: error in callback (ignoring): Wide character in syswrite at /usr/local/lib/x86_64-linux-gnu/perl/5.28.1/AnyEvent/Util.pm line 661.

VS Code ver. 1.54.1
Remote server debian 10.8
Local MacOS

Regards,
Ruslan

**Comment by richterger** [comment]
Can you please attach the file to reproduce the error here.

**Comment by ragnayev** [comment]
Hi Gerald,

thank you very much for the extension

screen capture
<https://www.dropbox.com/s/cot1k8c97rmpw3h/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202021-03-14%20%D0%B2%2021.01.27.png?dl=0>

Regards,
Ruslan

вс, 14 мар. 2021 г. в 18:41, Gerald Richter ***@***.***>:

**Comment by richterger** [comment]
Which encoding do you see at the bottom of VSCode?
Which is the encoding you are using? Is it utf-8 or ios8859-2 or anything else?
For me the file is opened as utf-8 and everything works fine?

**Comment by ragnayev** [comment]
It's UTF-8 encoding displays at the bottom of VSCode.

I checked it out right now again. Just added a word in Cyrillic and saved
the file.
The log file immediately starts growing and fills with many lines

*EV: error in callback (ignoring): Wide character in syswrite at
/usr/local/lib/x86_64-linux-gnu/perl/5.28.1/AnyEvent/Util.pm line 661.*





*EV: error in callback (ignoring): Wide character in syswrite at
/usr/local/lib/x86_64-linux-gnu/perl/5.28.1/AnyEvent/Util.pm line 661.EV:
error in callback (ignoring): Wide character in syswrite at
/usr/local/lib/x86_64-linux-gnu/perl/5.28.1/AnyEvent/Util.pm line 661.EV:
error in callback (ignoring): Wide character in syswrite at
/usr/local/lib/x86_64-linux-gnu/perl/5.28.1/AnyEvent/Util.pm line 661.EV:
error in callback (ignoring): Wide character in syswrite at
/usr/local/lib/x86_64-linux-gnu/perl/5.28.1/AnyEvent/Util.pm line 661.EV:
error in callback (ignoring): Wide character in syswrite at
/usr/local/lib/x86_64-linux-gnu/perl/5.28.1/AnyEvent/Util.pm line 661.*
*EV: error in callback (ignoring): Wide character in syswrite at
/usr/local/lib/x86_64-linux-gnu/perl/5.28.1/AnyEvent/Util.pm line 661.*


after I quit from VSCode, log file contains:

EV: error in callback (ignoring): Wide character in syswrite at
/usr/local/lib/x86_64-linux-gnu/perl/5.28.1/AnyEvent/Util.pm line 661.
LS: end aio read cnt=22
LS: line=<Content-Length: 58>
LS: line=<>
EV: error in callback (ignoring): Wide character in syswrite at
/usr/local/lib/x86_64-linux-gnu/perl/5.28.1/AnyEvent/Util.pm line 661.
LS: read data={"jsonrpc":"2.0","id":6,"method":"shutdown","params":null}
LS: read header={ "Content-Length" => 58 }
LS: ---> Request: {
   "method" : "shutdown",
   "id" : 6,
   "params" : null,
   "jsonrpc" : "2.0"
}

LS: handle_req id=6
Attribute (params) does not pass the type constraint because: Validation
failed for 'HashRef' with value undef at
/usr/local/lib/x86_64-linux-gnu/perl/5.28.1/Moose/Object.pm line 24
        Moose::Object::new('Perl::LanguageServer::Req',
'HASH(0x558849c8e7f0)') called at
/usr/local/share/perl/5.28.1/Perl/LanguageServer.pm line 250
        Perl::LanguageServer::__ANON__ at
/usr/lib/x86_64-linux-gnu/perl5/5.28/Coro.pm line 716
        Coro::_coro_run at -e line 0
LS: done handle_req id=6
Can't call method "logger" on an undefined value at
/usr/local/share/perl/5.28.1/Perl/LanguageServer.pm line 241 during global
destruction.

Regards,


вс, 11 июл. 2021 г. в 16:58, Gerald Richter ***@***.***>:

**Comment by richterger** [comment]
Could you please set logLevel to 2, restart vscode and post the full log output

**Comment by ragnayev** [comment]
The current LogLevel is already 2

LogLevel state <https://1drv.ms/u/s!AnBfo1WAClRC1gWHo4Q_8GBOcIJV?e=FRepZX>

вс, 11 июл. 2021 г. в 19:56, Gerald Richter ***@***.***>:

**Comment by richterger** [comment]
Should be fixed in 2.6.0+
