### ISSUE TITLE
No function available, following setup

### ISSUE THREAD

**Issue by solv-mork** [richterger/Perl-LanguageServer#77]
I like to use extension in following setup.
Windows 7 64Bits
ActivePerl 5.28, runtime build in own ActiveState Platform project 
Built ActivePerl runtime .msi downloaded from AS Platform then Perl runtime installed from .msi
VS Code version downloaded from Microsoft web recent days
Installed Perl runtime not placed to installed VS C
Perl::Language Server and Debugger by Gerald Richter installed from VS Code Extensions Manager

I need powerfull IDE for efficient navigation through symbols, lines and files of code. Lengthly Perl script (1100 loc), lot of sub-routines inside. Needed features : lists of symbols, call stack visualisation (outline? sorry, I am not current with wording), quick jumping between symbols, lines, references, definitions, declaration.... Script analysis.
It is fine for me to run Perl scripts outside VS C.

1. How are the odds to get Perl::Language Server and Debugger working in above setup?
2. Functions don't seem to be available in VS C GUI for installed Perl::Language Server and Debugger.
3. In some plugin marketplace one can read for this extension a statement in Q&A section this extension would need Language Server. This is the point where some questions arise:
Is it really multi-layer architercture: generic Language Server > language-specific Language Server > Client?
This plugin has wording "Language Server" in its name , hence generic one should be out-of-box?
If it applies, how to find and install generic Language Server ?
In case of setup used is it ActiveState Perl runtime where generic Language Server needs to be added to software stack?
Thanks in advance for all hints.

**Comment by richterger** [comment]
You need to install the Perl Module Perl::LanguageServer in your Perl installation. 
BUT, it not works perfectly on windows yet, due to issue with stdin/out on windows.
