### ISSUE TITLE
Language Server no longer starts up in VS Code 1.54.1

### ISSUE THREAD

**Issue by beltaurus** [richterger/Perl-LanguageServer#78]
On Linux (SuSE12), I just updated VS Code to Version 1.54.1.

My Perl/LanguageServer plugin seems to be unable to start:
```
[Error  - 00:54:44.906] Getting token failed: Error: Unknown or unsupported transport 'disabled' for address 'disabled:'
```

**Comment by richterger** [comment]
Just tested with 1.54.2 and I have no trouble using it.
Could you update to 1.54.2?

**Comment by beltaurus** [comment]
Updated. Don't see problem any longer...
