### ISSUE TITLE
Host Key verification not working

### ISSUE THREAD

**Issue by kt1040tr** [richterger/Perl-LanguageServer#85]
Running VS-Code on Windows to develope for Linux with Perl. Remote-SSH is running, I can connect via ssh and plink to my linux, but wenn I start VS-Code with a Perl-File I get the info about Languageserver could not start due to Host Key verification failed.
I do not understand why this failes.

Host key verification failed.
[Info  - 10:58:50 AM] Connection to server got closed. Server will restart.
Host key verification failed.
[Info  - 10:58:50 AM] Connection to server got closed. Server will restart.
Host key verification failed.
[Info  - 10:58:50 AM] Connection to server got closed. Server will restart.
Host key verification failed.
[Info  - 10:58:50 AM] Connection to server got closed. Server will restart.
Host key verification failed.
[Error - 10:58:50 AM] Connection to server got closed. Server will not be restarted.

**Comment by richterger** [comment]
Login to your system from the command line, so the hostkey is save in your known_hosts and afterwards it should work.
