### ISSUE TITLE
Format Document in vscode removes file contents

### ISSUE THREAD

**Issue by abraxxa** [richterger/Perl-LanguageServer#87]
This happens under fresh installed Perl 5.32.1 regardless of using perlbrew or plenv.
It did work as expected using Perl 5.26.1 installed by perlbrew.

While looking at the log level 2 output I realized that it uses perltidy under the hood which wasn't installed.

So the bug report is to either add Perl::Tidy as a dependency to Perl::LanguageServer or make it disable the 'Format Document' feature if Perl::Tidy isn't installed.

Thanks!

**Comment by davebaird** [comment]
I have the same issue on Perl v5.30.0 (Ubuntu OS). Perl::Tidy is installed and perl.perlInc in settings.json includes my local modules installation path. I've set perl.logLevel: 2 but there's no output. If I select some code and format selection, the selected code disappears. If I format the whole file, everything disappears. I also tried `sudo ln -s /home/dave/perl5/bin/perltidy /usr/bin/perltidy` in case the extension couldn't find perltidy but that didn't help.

**Comment by Direct-A** [comment]
I've got the same issue, but in vscode ouput I found this:

```log
LS: path_map = undef
LS: perlinc = ["/home/xxx/perl5/lib/perl5/"]
LS: file_filter_regex = "(?:\\.pm|\\.pl)\$"
LS: ignore_dir = { ".git" => 1, ".svn" => 1, ".vscode" => 1 }
LS: background_parser folders = {
  "file:///run/media/Data/OneDrive/On_Linux/bioinfo/learn_prel" => "/run/media/Data/OneDrive/On_Linux/bioinfo/learn_prel",
}
LS: apply_all_roles (Moose::Meta::Class::__ANON__::SERIAL::2=HASH(0x55dd5b264988), Perl::LanguageServer::Methods::textDocument, Perl/LanguageServer/Methods/textDocument.pm)
state_dir = /run/media/Data/OneDrive/On_Linux/bioinfo/learn_prel/.vscode/perl-lang
LS: initial parsing done, loaded 2 files, parsed  files, 2 files
LS: ERROR: Unknow perlmethod _rpcnot_setTraceNotification at /home/xxx/perl5/lib/perl5/Perl/LanguageServer.pm line 222.
```
