### ISSUE TITLE
Eliminate all log/warning/error messages?

### ISSUE THREAD

**Issue by muriloq** [richterger/Perl-LanguageServer#93]
Hi! 
Is there a way to disable all error / warning messages from the Console Output, leaving only stderr/stdout from the debugee? I understand they don't affect the debugger behavior, but it makes a lot harder to identify the real output  is correct. I tried to set `    "perl.logLevel": 0` but it didn't help.

Below are some examples of the unwanted messages. Thanks a lot in advance! 

```
DAx: connect from 127.0.0.1:59948
DAx: apply_all_roles (Perl::LanguageServer=HASH(0x11b5d840), Perl::LanguageServer::Methods::DebugAdapter, Perl/LanguageServer/Methods/DebugAdapter.pm)
DAI: session_id = 51cf8439-84a9-4884-9ab5-e03d9a2ba824
DAI: di_response seq = 1000000056 lastcmd seq = 1000000056 channels = [1000000056] queue size = 0
DA: ERROR: Debuggee is running at /home/utils/perl5/perlbrew/perls/5.26.2-065/lib/site_perl/5.26.2/Perl/LanguageServer/Methods/DebugAdapter.pm line 245.
LS: ERROR: Unknow perlmethod _rpcnot_setTraceNotification at /home/utils/perl5/perlbrew/perls/5.26.2-065/lib/site_perl/5.26.2/Perl/LanguageServer.pm line 222.
LS: path_map = undef
LS: perlinc = [
  "/home/utils/perl-5.26/5.26.2-065/",
]
LS: file_filter_regex = "(?:)\$"
LS: ignore_dir = { ".git" => 1, ".svn" => 1, ".vscode" => 1 }
```

**Comment by richterger** [comment]
The Log of Perl::LanguageServer goes to the LangauageServer Ouput pane and the Output (stdout & stderr) of the debugee goes to the Debugger Console, so they are clearly separated. So I don't understand what the problem is?

**Comment by muriloq** [comment]
I'm very sorry, I chose the wrong option. Instead of looking at the "Debug Console" tab, which indeed shows only stdout/stderr of my program, I was looking at the "Output" tab, after choosing the "Perl Language Server" in the combo box. We may close this as "not a bug"/ PEBKAC! ;-)
