### ISSUE TITLE
Submit extension to Open-VSX ?

### ISSUE THREAD

**Issue by djzort** [richterger/Perl-LanguageServer#98]
The https://open-vsx.org repository hosts "Extensions for VS Code Compatible Editors" like VSCodium.

Could you please upload the perl VSCode extension to that repo? Thanks.

**Comment by richterger** [comment]
The site seems to have problems at the moment. I will do it for the next release.

**Comment by struanb** [comment]
Hi @richterger. Any update on this issue? It would be a great help for our team to have the latest version of the extension available on the Open VSX registry. We develop in Eclipse Theia using [Dockside](https://dockside.io) and currently we have to manually check for updates and download the extension into our development environment whenever we find a new version. Adding it would allow us to use `extensions.json` to 'recommend' the extension to our developers, so they can install the latest version whenever they need it.

**Comment by richterger** [comment]
2.6.1 is now pulished on https://open-vsx.org/extension/richterger/perl
